// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3de4639f-19cb-4257-92c8-c80ef1e5b625",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2lkcIx8IK",
    "aws_user_pools_web_client_id": "u21q4t1ui4h0skqerdjv0u8de",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://x5fp4fq6ovdcpavigxk276qypy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-szxw77xcpnflxi24xevvhj3g5m"
};


export default awsmobile;
